name: Django CI

on:
  push:
    branches: [ "master", "develop" ]
  pull_request:
    branches: [ "master", "develop" ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.9, 3.10]

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run Tests
      env: 
        SECRET_KEY: ${{ secrets.SECRET_KEY }}
        FIREBASE_SERVICE_ACCOUNT: ${{ secrets.FIREBASE_SERVICE_ACCOUNT }}
        FIREBASE_WEBAPP_CONFIG: ${{ secrets.FIREBASE_WEBAPP_CONFIG }}
        REVENUE_CAT_API_KEY: ${{ secrets.REVENUE_CAT_API_KEY }}
        
        DOMAIN: ${{ secrets.DOMAIN }}
        DOMAIN_IP: ${{ secrets.DOMAIN_IP }}
        TESTING_DOMAIN: ${{ secrets.TESTING_DOMAIN }}
        
        EMAIL_HOST: ${{ secrets.EMAIL_HOST }}
        EMAIL_PORT: ${{ secrets.EMAIL_PORT }}
        EMAIL_HOST_USER: ${{ secrets.EMAIL_HOST_USER }}
        EMAIL_HOST_PASSWORD: ${{ secrets.EMAIL_HOST_PASSWORD }}
        PROSIT_ADMIN_EMAIL: ${{ secrets.PROSIT_ADMIN_EMAIL }}
      
      run: |
        pytest
